name: Run Tests

on:
  push:
    branches:
      - main # Change this to the branch where you want to run the tests
  pull_request:
    branches:
      - main # Also run tests on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x] # You can specify which Node.js versions to test against

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Upload test results (if any)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results
